# Generated by Django 2.1.7 on 2022-07-22 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=255)),
                ('bdate', models.DateField(auto_now_add=True)),
                ('bnumpag', models.CharField(max_length=255)),
                ('bprod', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'book',
            },
        ),
    ]
