# Generated by Django 2.1.7 on 2022-07-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20220722_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='numero_pagina',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
