# Generated by Django 2.1.7 on 2022-07-22 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalog',
            old_name='cdate',
            new_name='data_criacao',
        ),
        migrations.RenameField(
            model_name='catalog',
            old_name='cname',
            new_name='nome',
        ),
    ]
